# Generated by Django 5.2.1 on 2025-05-29 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('data_nascimento', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='Sem titulo')),
                ('descricao', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('data_subconferencia', models.TextField(blank=True, null=True)),
                ('qtd_propostas', models.IntegerField(default=0)),
                ('perguntas', models.TextField(blank=True, null=True)),
                ('respostas', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('qtd_propostas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('cidade', models.CharField(max_length=100)),
                ('qtd_propostas', models.IntegerField(default=0)),
                ('qtd_comentarios', models.IntegerField(default=0)),
                ('qtd_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('qtd_propostas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Curtidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtido', models.BooleanField(default=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comentarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_etapa', models.CharField(max_length=200)),
                ('descricao_etapa', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('regiao_etapa', models.CharField(default='não informado', max_length=100)),
                ('duracao_etapa', models.CharField(max_length=100)),
                ('qtd_propostas_etapa', models.IntegerField(default=0, null=True)),
                ('qtd_inscritos_etapa', models.IntegerField(default=0, null=True)),
                ('url_etapa', models.TextField(blank=True, null=True)),
                ('propostas_relacionadas', models.TextField(blank=True, null=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='idPerfilUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.perfil'),
        ),
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_proposta', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descricao_proposta', models.TextField()),
                ('qtd_votos', models.IntegerField(default=0)),
                ('url_proposta', models.URLField(blank=True, null=True)),
                ('conferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conferencia')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consultas')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etapas')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.planos')),
            ],
        ),
    ]
