# Generated by Django 5.2.1 on 2025-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
