# Generated by Django 5.2.1 on 2025-06-22 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pergunta')),
                ('resposta_multipla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.alternativa')),
                ('resposta_simples', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.perguntasimnao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'pergunta')},
            },
        ),
    ]
