# Generated by Django 5.2.1 on 2025-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conferencia_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='url_etapa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
