# Generated by Django 5.2.1 on 2025-06-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_compromisso', models.CharField(max_length=255, verbose_name='Nome do Compromisso')),
                ('data_compromisso', models.DateField(verbose_name='Data do Compromisso')),
                ('agendado', models.BooleanField(default=True, verbose_name='Está Agendado?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['data_compromisso'],
            },
        ),
    ]
