# Generated by Django 5.2.1 on 2025-05-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_etapas_url_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='url_etapa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
