# Generated by Django 5.2.1 on 2025-05-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_etapas_url_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='titulo_etapa',
            field=models.CharField(max_length=500),
        ),
    ]
