# Generated by Django 5.2.1 on 2025-05-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_etapas_titulo_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='regiao_etapa',
            field=models.CharField(default='não informado', max_length=250),
        ),
    ]
