# Generated by Django 5.2.1 on 2025-05-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_etapas_regiao_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='planos',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
