# Generated by Django 5.2.1 on 2025-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_consultas_link_alter_consultas_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostas',
            name='titulo_proposta',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='propostas',
            name='url_proposta',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
