# Generated by Django 5.2.1 on 2025-05-31 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_propostas_titulo_proposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='conferencia',
            name='respostas',
        ),
        migrations.CreateModel(
            name='PerguntasParticipativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas', models.TextField()),
                ('respostas', models.TextField()),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conferencia')),
            ],
        ),
    ]
