version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=participemais
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=unbook
      - POSTGRES_HOST=db      
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: participemais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unbook
    ports:
      - "5433:5432"
