version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    ports:
      - "8000:8000"
    volumes:
      - static:/app/backend/static
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      DJANGO_ENV: prod
      ROLE: backend
      DEBUG: "False"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    depends_on:
      - db

  importer:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    volumes:
      - ./backend:/app/backend
      - ./WebScraper:/app/WebScraper
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      DJANGO_ENV: prod
      ROLE: importer
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  pgdata:
  static:
