FROM python:3.10-slim

# Define o diretório de trabalho como /app
WORKDIR /app

# Copia apenas o requirements.txt e instala as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do projeto
COPY . .

# Define a variável de ambiente com o módulo settings
ENV DJANGO_SETTINGS_MODULE=project.settings

EXPOSE 8000

# Executa o Django a partir da pasta backend
CMD ["python3", "backend/manage.py", "runserver", "0.0.0.0:8000"]
