version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./backend:/app/backend
      - ./WebScraper:/app/WebScraper
    ports:
      - "${APP_PORT}:8000"
    environment:
      DJANGO_ENV: dev
      ROLE: backend
      DEBUG: "${DEBUG}"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - db

  importer:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./backend:/app/backend
      - ./WebScraper:/app/WebScraper
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - db
    environment:
      DJANGO_ENV: dev
      ROLE: importer
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db

volumes:
  pgdata:
