FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app


RUN apt-get update && apt-get install -y gcc libpq-dev netcat-openbsd postgresql-client && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000

ENV PYTHONPATH="${PYTHONPATH}:/app/backend"


ENTRYPOINT ["/entrypoint.sh"]
CMD []