# Generated by Django 5.2.1 on 2025-07-05 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oficina', models.CharField(max_length=500)),
                ('descricao_oficina', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('regiao_oficina', models.CharField(default='não informado', max_length=250)),
                ('duracao_oficina', models.CharField(default='não informado', max_length=100)),
                ('qtd_propostas_oficina', models.IntegerField(default=0, null=True)),
                ('qtd_inscritos_oficina', models.IntegerField(default=0, null=True)),
                ('propostas_relacionadas', models.TextField(blank=True, null=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.planos')),
            ],
        ),
    ]
