# Generated by Django 5.2.3 on 2025-07-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_oficinas'),
        ('propostas', '0006_categoria_remove_propostas_topicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='planos', to='propostas.categoria'),
        ),
        migrations.AddField(
            model_name='planos',
            name='palavras_chaves',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
