# Generated by Django 5.2.1 on 2025-07-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_planos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='palavras_chaves',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
