# Generated by Django 5.2.3 on 2025-07-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_planos_palavras_chaves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planos',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
