# Generated by Django 5.2.1 on 2025-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('qtd_propostas', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
