# Generated by Django 5.2.1 on 2025-07-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('propostas', '0005_categoria_topico_propostas_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='propostas.categoria'),
        ),
    ]
