# Generated by Django 5.2.1 on 2025-07-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consultas_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='palavras_chaves',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
