# Generated by Django 5.2.1 on 2025-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consultas_categorias_consultas_palavras_chaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='palavras_chaves',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
