# Generated by Django 5.2.1 on 2025-06-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='Sem titulo')),
                ('descricao', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('data_subconferencia', models.TextField(blank=True, null=True)),
                ('qtd_propostas', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_etapa', models.CharField(max_length=500)),
                ('descricao_etapa', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('regiao_etapa', models.CharField(default='não informado', max_length=250)),
                ('duracao_etapa', models.CharField(max_length=100)),
                ('qtd_propostas_etapa', models.IntegerField(default=0, null=True)),
                ('qtd_inscritos_etapa', models.IntegerField(default=0, null=True)),
                ('url_etapa', models.URLField(blank=True, max_length=500, null=True)),
                ('propostas_relacionadas', models.TextField(blank=True, null=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencias.conferencia')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasParticipativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas', models.TextField()),
                ('respostas', models.TextField()),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencias.conferencia')),
            ],
        ),
    ]
