# Generated by Django 5.2.1 on 2025-06-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0002_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferencias.conferencia'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferencias.etapas'),
        ),
    ]
