# Generated by Django 5.2.1 on 2025-06-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0004_alter_conferencia_data_subconferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='duracao_etapa',
            field=models.CharField(default='não informado', max_length=100),
        ),
    ]
