# Generated by Django 5.2.1 on 2025-06-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0005_alter_etapas_duracao_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='data_subconferencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapas',
            name='duracao_etapa',
            field=models.CharField(default='não informado', max_length=100),
        ),
    ]
