# Generated by Django 5.2.1 on 2025-06-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0006_alter_conferencia_data_subconferencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
