# Generated by Django 5.2.1 on 2025-07-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0007_delete_agenda'),
        ('propostas', '0005_categoria_topico_propostas_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='conferencias', to='propostas.categoria'),
        ),
    ]
