# Generated by Django 5.2.1 on 2025-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0008_conferencia_categorias_conferencia_palavras_chaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='palavras_chaves',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
