# Generated by Django 5.2.1 on 2025-07-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0009_conferencia_palavras_chaves'),
        ('propostas', '0006_categoria_nuvem_palavras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='categorias',
        ),
        migrations.AddField(
            model_name='conferencia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='propostas.categoria'),
        ),
    ]
