# Generated by Django 5.0.4 on 2025-05-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_email_alter_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem_url', models.URLField(max_length=500)),
                ('sobre', models.TextField()),
                ('qtd_propostas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('regiao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('qtd_propostas', models.IntegerField()),
                ('qtd_inscritos', models.IntegerField()),
                ('url_proposta_relacionada', models.URLField(max_length=500)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='usuarios.conferencia')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaParticipativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('resposta', models.TextField()),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='usuarios.conferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('autor_nome', models.CharField(max_length=255)),
                ('qtd_votos', models.IntegerField()),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='usuarios.conferencia')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='usuarios.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='usuarios.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comentario', 'usuario')},
            },
        ),
    ]
