# Generated by Django 5.2.1 on 2025-06-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comunidade.chat'),
        ),
        migrations.AlterUniqueTogether(
            name='curtidas',
            unique_together={('usuario', 'comentario')},
        ),
    ]
