# Generated by Django 5.2.1 on 2025-06-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferencias', '0001_initial'),
        ('consultas', '0001_initial'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_proposta', models.CharField(max_length=400)),
                ('autor', models.CharField(max_length=100)),
                ('descricao_proposta', models.TextField()),
                ('qtd_votos', models.IntegerField(default=0)),
                ('url_proposta', models.URLField(blank=True, max_length=500, null=True)),
                ('conferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferencias.conferencia')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.consultas')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferencias.etapas')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planos.planos')),
            ],
        ),
    ]
