# Generated by Django 5.2.1 on 2025-06-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palavras_chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavras', models.CharField(max_length=500)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_chave', to='propostas.propostas')),
            ],
        ),
    ]
