# Generated by Django 5.2.1 on 2025-06-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='favorito',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
