# Generated by Django 5.2.1 on 2025-06-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0003_propostas_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostas',
            name='favorito',
        ),
    ]
