# Generated by Django 5.2.1 on 2025-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_remove_propostas_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='propostas',
            name='topicos',
            field=models.ManyToManyField(blank=True, related_name='propostas', to='propostas.topico'),
        ),
    ]
