# Generated by Django 5.2.3 on 2025-07-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0005_topico_propostas_topicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nuvem_palavras', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='propostas',
            name='topicos',
        ),
        migrations.AddField(
            model_name='propostas',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='propostas', to='propostas.categoria'),
        ),
    ]
