# Generated by Django 5.2.1 on 2025-07-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0005_categoria_topico_propostas_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nuvem_palavras',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
