# Generated by Django 5.2.1 on 2025-07-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0006_categoria_remove_propostas_topicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='topicos',
            field=models.ManyToManyField(blank=True, related_name='propostas', to='propostas.topico'),
        ),
    ]
