# Generated by Django 5.2.1 on 2025-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_usuario_favoritos'),
        ('propostas', '0004_remove_propostas_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritas', to='propostas.propostas'),
        ),
    ]
