# Generated by Django 5.2.1 on 2025-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_usuario_favoritos'),
        ('conferencias', '0006_alter_conferencia_data_subconferencia_and_more'),
        ('consultas', '0001_initial'),
        ('planos', '0002_oficinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='conferencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_conferencias', to='conferencias.conferencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='consultas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_consultas', to='consultas.consultas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='planos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_planos', to='planos.planos'),
        ),
    ]
