name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ParticipeMais/requirements.txt
        pip install pylint
        pip install pylint-django

    - name: Analysing the code with pylint (min score 7.0)
      run: |
          export DJANGO_SETTINGS_MODULE=backend.project.settings
          export PYTHONPATH=.
          echo "Running Pylint..."
          pylint $(git ls-files '*.py') --score=y --exit-zero | tee pylint.log
          SCORE=$(tail -n 2 pylint.log | grep 'Your code has been rated at' | awk '{print $7}' | cut -d/ -f1)
          echo "Pylint score: $SCORE"
          MIN_SCORE=7.0
          RESULT=$(echo "$SCORE >= $MIN_SCORE" | bc -l)
          if [ "$RESULT" -eq 1 ]; then
            echo "✅ Pylint passed with score $SCORE"
          else
            echo "❌ Pylint failed: score $SCORE is less than minimum required $MIN_SCORE"
            exit 1
          fi
