name: Lint

on:
  push:
    branches: [ main, desenvolvimento ]
  pull_request:
    branches: [ main, desenvolvimento ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci || npm install
        working-directory: ./frontEnd/projeto/participe-mais

      - name: Run ESLint
        run: |
          npm run lint
        working-directory: ./frontEnd/projeto/participe-mais
